--Ignored Items will be set here

PLUGIN.ignored = {
  "psihelem",

  "banditexonondrop",
  "banditkombeznondrop",
  "clearskycs3anondrop",
  "clearskyexonondrop",
  "freedomexonondrop",
  "name1",
  "freedomberillnondrop",
  "ecologsspnondrop",
  "dolgexonondrop",
  "dolgbronanondrop",
  "militaryexonondrop",
  "militarybulatnondrop",
  "merceexonondrop",
  "lastdayexonondrop",
  "hunterexonodrop",
  "smotriteliexonondrop",
  "stalkerexonondrop",
  "сhzo",
  "pda_bandit",
  "pda_duty",
  "docsbu",
  "kowelek",
  "pda_freedom",
  "pda_loner",
  "pda_merc",
  "pda_military",
  "pda_monolith",
  "pda_zombi",
  
  "agro_svalka",
  "armysklad_bar",
  "bar_armysklad",
  "bar_svalka",
  "svalka_agro",
  "svalka_bar",
  
  "animal",
  "fnfs2000",
  "deagle",
  "gaus",
  "knife",
  "otboinik",
  "rish",
  "rpg7",
  "rpg7",
  "velesnondrop",
  "wtorm",
  
  "vipkit"
}
