--[[
	Define your voice classes here. The function goes:

	nut.voice.defineClass(class, onCheck(client)[, onModify(client, sounds)])

	Class is the same class that starts the nut.voice.register
	It is case-insensitive. The onCheck passes the player trying
	to use the class. Return true to allow them to use the class.
--]]

-- What type of chat modes support voice commands:
nut.voice.chatTypes["ic"] = true
nut.voice.chatTypes["w"] = true
nut.voice.chatTypes["y"] = true
nut.voice.chatTypes["radio"] = true
nut.voice.chatTypes["dispatch"] = true

nut.voice.defineClass("combine", function(client)
	return client:isCombine()
end, function(client, sounds, chatType)
	if (chatType == "dispatch" or client:isCombineRank("SCN")) then
		return false
	end

	local beeps = SCHEMA.beepSounds[client:Team()] or SCHEMA.beepSounds[FACTION_CP]

	table.insert(sounds, 1, {(table.Random(beeps.on)), 0.25})
	sounds[#sounds + 1] = {(table.Random(beeps.off)), nil, 0.25}
end)

nut.voice.defineClass("dispatch", function(client)
	return SCHEMA:isDispatch(client)
end, function(client, sounds, chatType)
	if (chatType != "dispatch") then
		return false
	end
end, true)

nut.voice.register("combine", "атака_одиночки", "", {"stalk/attack_1.wav", "stalk/attack_2.wav", "stalk/attack_3.wav", "stalk/attack_4.wav", "stalk/attack_5.wav", "stalk/attack_6.wav"})
nut.voice.register("combine", "смех_одиночки", "", {"stalk/laughter_1.wav", "stalk/laughter_2.wav", "stalk/laughter_3.wav", "stalk/laughter_4.wav", "stalk/laughter_5.wav", "stalk/laughter_6.wav"})
nut.voice.register("combine", "анекдот_одиночка", "", {"stalk/joke_1.wav", "stalk/joke_2.wav", "stalk/joke_3.wav", "stalk/joke_4.wav", "stalk/joke_5.wav", "stalk/joke_6.wav", "stalk/joke_7.wav", "stalk/joke_8.wav", "stalk/joke_9.wav", "stalk/joke_10.wav", "stalk/joke_11.wav", "stalk/joke_12.wav", "stalk/joke_13.wav"})
nut.voice.register("combine", "ожидать_одиночка", "", {"stalk/idle_1.wav", "stalk/idle_2.wav", "stalk/idle_3.wav", "stalk/idle_4.wav", "stalk/idle_5.wav", "stalk/idle_6.wav", "stalk/idle_7.wav", "stalk/idle_8.wav", "stalk/idle_9.wav", "stalk/idle_10.wav", "stalk/idle_11.wav", "stalk/idle_12.wav", "stalk/idle_13.wav", "stalk/idle_14.wav", "stalk/idle_15.wav", "stalk/idle_16.wav", "stalk/idle_17.wav", "stalk/idle_18.wav", "stalk/idle_19.wav", "stalk/idle_20.wav", "stalk/idle_21.wav", "stalk/idle_22.wav", "stalk/idle_23.wav", "stalk/idle_24.wav", "stalk/idle_25.wav", "stalk/idle_26.wav", "stalk/idle_27.wav", "stalk/idle_28.wav", "stalk/idle_29.wav", "stalk/idle_30.wav", "stalk/idle_31.wav", "stalk/idle_32.wav", "stalk/idle_33.wav", "stalk/idle_34.wav", "stalk/idle_35.wav", "stalk/idle_36.wav", "stalk/idle_37.wav", "stalk/idle_38.wav"})
nut.voice.register("combine", "хороший_хараб_одиночка", "", {"stalk/loot_good_1.wav", "stalk/loot_good_2.wav", "stalk/loot_good_3.wav"})
nut.voice.register("combine", "поиск_хабара_одиночка", "", {"stalk/loot_begin_1.wav", "stalk/loot_begin_2.wav", "stalk/loot_begin_3.wav"})
nut.voice.register("combine", "плохой_хараб_одиночка", "", {"stalk/loot_bad_1.wav", "stalk/loot_bad_2.wav", "stalk/loot_bad_3.wav"})
nut.voice.register("combine", "добавать_одиночка", "", {"stalk/kill_wounded_1.wav", "stalk/kill_wounded_2.wav", "stalk/kill_wounded_3.wav", "stalk/kill_wounded_4.wav", "stalk/kill_wounded_5.wav"})
nut.voice.register("combine", "помогите_одиночка", "", {"stalk/help_1.wav", "stalk/help_2.wav", "stalk/help_3.wav", "stalk/help_4.wav", "stalk/help_5.wav"})
nut.voice.register("combine", "плохая_шутка_одиночка", "", {"stalk/reaction_joke_1.wav", "stalk/reaction_joke_2.wav"})
nut.voice.register("combine", "оружие_одиночка", "", {"stalk/dropweapon_1.wav", "stalk/dropweapon_2.wav", "stalk/dropweapon_3.wav", "stalk/dropweapon_4.wav", "stalk/dropweapon_5.wav"})
nut.voice.register("combine", "обходи_одиночка", "", {"stalk/detour_1.wav","stalk/detour_2.wav","stalk/detour_3.wav","stalk/detour_4.wav","stalk/detour_5.wav"})
nut.voice.register("combine", "искать_одиночка", "", {"stalk/search_1.wav","stalk/search_2.wav","stalk/search_3.wav","stalk/search_4.wav","stalk/search_5.wav","stalk/search_6.wav","stalk/search_7.wav"})
nut.voice.register("combine", "лечить_одиночка", "", {"stalk/medkit_1.wav","stalk/medkit_2.wav","stalk/medkit_3.wav"})
nut.voice.register("combine", "спасибо_одиночка", "", {"stalk/thanx_1.wav","stalk/thanx_2.wav","stalk/thanx_3.wav"})
nut.voice.register("combine", "лидеру_одиночка", "", {"stalk/meet_use_no_talk_leader_1.wav","stalk/meet_use_no_talk_leader_2.wav","stalk/meet_use_no_talk_leader_3.wav"})
nut.voice.register("combine", "привет_одиночка", "", {"stalk/meet_hello_1.wav","stalk/meet_hello_2.wav","stalk/meet_hello_3.wav"})
nut.voice.register("combine", "отвали_одиночка", "", {"stalk/meet_use_no_default_1.wav","stalk/meet_use_no_default_2.wav","stalk/meet_use_no_default_3.wav"})
nut.voice.register("combine", "враг_одиночка", "", {"stalker/enemy_1.wav","stalker/enemy_2.wav","stalker/enemy_3.wav","stalker/enemy_4.wav","stalker/enemy_5.wav","stalker/enemy_6.wav","stalker/enemy_7.wav","stalker/enemy_8.wav","stalker/enemy_9.wav","stalker/enemy_10.wav"})
nut.voice.register("combine", "враг_убит_одиночка", "", {"stalker/enemy_down_1.wav","stalker/enemy_down_2.wav","stalker/enemy_down_3.wav","stalker/enemy_down_4.wav","stalker/enemy_down_5.wav","stalker/enemy_down_6.wav","stalker/enemy_down_7.wav"})
nut.voice.register("combine", "враг_ранен_одиночка", "", {"stalker/enemy_hit_1.wav","stalker/enemy_hit_2.wav","stalker/enemy_hit_3.wav","stalker/enemy_hit_4.wav","stalker/enemy_hit_5.wav","stalker/enemy_hit_6.wav"})
nut.voice.register("combine", "враг_потерян_одиночка", "", {"stalker/enemy_lost_1.wav","stalker/enemy_lost_2.wav","stalker/enemy_lost_3.wav","stalker/enemy_lost_4.wav","stalker/enemy_lost_5.wav","stalker/enemy_lost_6.wav","stalker/enemy_lost_7.wav","stalker/enemy_lost_8.wav"})
nut.voice.register("combine", "союзник_ранен_одиночка", "", {"stalker/hit_friend_1.wav","stalker/hit_friend_2.wav","stalker/hit_friend_3.wav","stalker/hit_friend_4.wav"})
nut.voice.register("combine", "бой_окончен_одиночка", "", {"stalker/relax_1.wav","stalker/relax_2.wav","stalker/relax_3.wav"})
nut.voice.register("combine", "союзник_убит_одиночка", "", {"stalker/tolls_1.wav","stalker/tolls_2.wav","stalker/tolls_3.wav","stalker/tolls_4.wav","stalker/tolls_5.wav"})
nut.voice.register("combine", "осмотреться_одиночка", "", {"stalker/wait_1.wav","stalker/wait_2.wav","stalker/wait_3.wav","stalker/wait_4.wav","stalker/wait_5.wav"})

nut.voice.register("combine", "смех_ренегаты", "", {"band/laughter_1.wav", "band/laughter_2.wav", "band/laughter_3.wav", "band/laughter_4.wav", "band/laughter_5.wav", "band/laughter_6.wav", "band/laughter_7.wav"})
nut.voice.register("combine", "атака_ренегаты", "", {"band/attack_1.wav", "band/attack_2.wav", "band/attack_3.wav", "band/attack_4.wav", "band/attack_5.wav", "band/attack_6.wav", "band/attack_7.wav", "band/attack_8.wav", "band/attack_9.wav"})
nut.voice.register("combine", "анекдот_ренегат", "", {"band/joke_1.wav", "band/joke_2.wav", "band/joke_3.wav", "band/joke_4.wav", "band/joke_5.wav", "band/joke_6.wav", "band/joke_7.wav", "band/joke_8.wav", "band/joke_9.wav"})
nut.voice.register("combine", "ожидание_одиночка", "", {"band/idle_1.wav", "band/idle_2.wav", "band/lidle_3.wav", "band/idle_4.wav", "band/idle_5.wav", "band/idle_6.wav", "band/idle_7.wav", "band/idle_8.wav", "band/idle_9.wav", "band/idle_10.wav", "band/idle_11.wav", "band/idle_12.wav", "band/idle_13.wav", "band/idle_14.wav", "band/idle_15.wav", "band/idle_16.wav", "band/idle_17.wav", "band/idle_18.wav", "band/idle_19.wav", "band/idle_20.wav", "band/idle_21.wav", "band/idle_22.wav", "band/idle_23.wav", "band/idle_24.wav", "band/idle_25.wav", "band/idle_26.wav", "band/idle_27.wav", "band/idle_28.wav", "band/idle_29.wav", "band/idle_30.wav", "band/idle_31.wav", "band/idle_32.wav", "band/idle_33.wav", "band/idle_34.wav", "band/idle_35.wav"})
nut.voice.register("combine", "хороший_хабар_ренегат", "", {"band/loot_good_1.wav", "band/loot_good_2.wav", "band/loot_good_3.wav"})
nut.voice.register("combine", "поиск_харабар_ренегат", "", {"band/loot_begin_1.wav", "band/loot_begin_2.wav", "band/loot_begin_3.wav"})
nut.voice.register("combine", "плохой_хабар_ренегат", "", {"band/loot_bad_1.wav", "band/loot_bad_2.wav", "band/loot_bad_3.wav"})
nut.voice.register("combine", "плохая_шутка_ренегат", "", {"band/reaction_joke_1.wav", "band/reaction_joke_2.wav", "band/reaction_joke_3.wav"})
nut.voice.register("combine", "добивание_ренегат", "", {"band/kill_wounded_1.wav", "band/kill_wounded_2.wav", "band/kill_wounded_3.wav", "band/kill_wounded_4.wav"})
nut.voice.register("combine", "помогите_роенегат", "", {"band/help_1.wav", "band/help_2.wav", "band/help_3.wav", "band/help_4.wav", "band/help_5.wav", "band/help_6.wav", "band/help_7.wav"})
nut.voice.register("combine", "обходи_ренегат", "", {"band/detour_1.wav","band/detour_2.wav","band/detour_3.wav","band/detour_4.wav","band/detour_5.wav","band/detour_6.wav","band/detour_7.wav","band/detour_8.wav","band/detour_9.wav","band/detour_10.wav"})
nut.voice.register("combine", "поиск_противника_ренегат", "", {"band/search_1.wav","band/search_2.wav","band/search_3.wav","band/search_4.wav","band/search_5.wav","band/search_6.wav","band/search_7.wav"})
nut.voice.register("combine", "лечить_ренегат", "", {"band/medkit_1.wav","band/medkit_2.wav","band/medkit_3.wav"})
nut.voice.register("combine", "спасибо_ренегат", "", {"band/thanx_1.wav","band/thanx_2.wav","band/thanx_3.wav"})
nut.voice.register("combine", "к_лидеру_ренегат", "", {"band/meet_use_no_talk_leader_1.wav","band/meet_use_no_talk_leader_2.wav","band/meet_use_no_talk_leader_3.wav"})
nut.voice.register("combine", "привет_ренегат", "", {"band/meet_hello_1.wav","band/meet_hello_2.wav","band/meet_hello_3.wav"})
nut.voice.register("combine", "отвали_ренегат", "", {"band/meet_use_no_default_1.wav","band/meet_use_no_default_2.wav","band/meet_use_no_default_3.wav"})
nut.voice.register("combine", "оружие_ренегат", "", {"band/dropweapon_1.wav", "band/dropweapon_2.wav", "band/dropweapon_3.wav", "band/dropweapon_4.wav", "band/dropweapon_5.wav", "band/dropweapon_6.wav"})
nut.voice.register("combine", "враг_ренегат", "", {"band/enemy_1.wav","band/enemy_2.wav","band/enemy_3.wav","band/enemy_4.wav","band/enemy_5.wav","band/enemy_6.wav","band/enemy_7.wav","band/enemy_8.wav","band/enemy_9.wav","band/enemy_10.wav","band/enemy_11.wav","band/enemy_12.wav"})
nut.voice.register("combine", "окончание_боя_ренегат", "", {"band/relax_1.wav","band/relax_2.wav","band/relax_3.wav"})
nut.voice.register("combine", "союзник_убит_ренегат", "", {"band/tolls_1.wav","band/tolls_2.wav","band/tolls_3.wav","band/tolls_4.wav","band/tolls_5.wav"})
nut.voice.register("combine", "осмотреться_ренегат", "", {"band/wait_1.wav","band/wait_2.wav","band/wait_3.wav","band/wait_4.wav","band/wait_5.wav"})

nut.voice.register("combine", "атака_свобода", "", {"free/attack_1.wav", "free/attack_2.wav", "free/attack_3.wav", "free/attack_4.wav", "free/attack_5.wav"})
nut.voice.register("combine", "анекдот_свобода", "", {"free/joke_1.wav", "free/joke_2.wav", "free/joke_3.wav", "free/joke_4.wav", "free/joke_5.wav", "free/joke_6.wav", "free/joke_7.wav", "free/joke_8.wav", "free/joke_9.wav", "free/joke_10.wav", "free/joke_11.wav", "free/joke_12.wav", "free/joke_13.wav", "free/joke_14.wav"})
nut.voice.register("combine", "смех_свобода", "", {"free/laughter_1.wav", "free/laughter_2.wav", "free/laughter_3.wav", "free/laughter_4.wav", "free/laughter_5.wav", "free/laughter_6.wav", "free/laughter_7.wav"})
nut.voice.register("combine", "хороший_хабар_свобода", "", {"free/loot_good_1.wav", "free/loot_good_2.wav", "free/loot_good_3.wav"})
nut.voice.register("combine", "ожидание_свобода", "", {"free/idle_1.wav", "free/idle_2.wav", "free/idle_3.wav", "free/idle_4.wav", "free/idle_5.wav", "free/idle_6.wav", "free/idle_7.wav", "free/idle_8.wav", "free/idle_9.wav", "free/idle_10.wav", "free/idle_11.wav", "free/idle_12.wav", "free/idle_13.wav", "free/idle_14.wav", "free/idle_15.wav", "free/idle_16.wav", "free/idle_17.wav", "free/idle_18.wav", "free/idle_19.wav", "free/idle_20.wav", "free/idle_21.wav", "free/idle_22.wav", "free/idle_23.wav", "free/idle_24.wav", "free/idle_25.wav", "free/idle_26.wav", "free/idle_27.wav", "free/idle_28.wav", "free/idle_29.wav", "free/idle_30.wav", "free/idle_31.wav", "free/idle_32.wav", "free/idle_33.wav", "free/idle_34.wav", "free/idle_35.wav", "free/idle_36.wav", "free/idle_37.wav", "free/idle_38.wav", "free/idle_39.wav", "free/idle_40.wav", "free/idle_41.wav", "free/idle_42.wav"})
nut.voice.register("combine", "поиск_хараба_свобода", "", {"free/loot_begin_1.wav", "free/loot_begin_2.wav", "free/loot_begin_3.wav"})
nut.voice.register("combine", "плохая_шутка_свобода", "", {"free/reaction_joke_1.wav", "free/reaction_joke_2.wav", "free/reaction_joke_3.wav", "free/reaction_joke_4.wav"})
nut.voice.register("combine", "плохой_хараб_свобода", "", {"free/loot_bad_1.wav", "free/loot_bad_2.wav", "free/loot_bad_3.wav"})
nut.voice.register("combine", "добавиние_свобода", "", {"free/kill_wounded_1.wav", "free/kill_wounded_2.wav", "free/kill_wounded_3.wav"})
nut.voice.register("combine", "помогите_свобода", "", {"free/help_1.wav", "free/help_2.wav", "free/help_3.wav", "free/help_4.wav", "free/help_5.wav", "free/help_6.wav", "free/help_7.wav", "free/help_8.wav", "free/help_9.wav", "free/help_10.wav", "free/help_11.wav", "free/help_12.wav", "free/help_13.wav"})
nut.voice.register("combine", "оружие_убрал_свобода", "", {"free/dropweapon_1.wav", "free/dropweapon_2.wav", "free/dropweapon_3.wav", "free/dropweapon_4.wav", "free/dropweapon_5.wav", "free/dropweapon_6.wav", "free/dropweapon_7.wav"})
nut.voice.register("combine", "обходи_свобода", "", {"free/detour_1.wav","free/detour_2.wav","free/detour_3.wav","free/detour_4.wav","free/detour_5.wav","free/detour_6.wav","free/detour_7.wav","free/detour_8.wav","free/detour_9.wav","free/detour_10.wav"})
nut.voice.register("combine", "поиск_противника_свобода", "", {"free/search_1.wav","free/search_2.wav","free/search_3.wav","free/search_4.wav","free/search_5.wav","free/search_6.wav","free/search_7.wav","free/search_8.wav"})
nut.voice.register("combine", "лечить_свобода", "", {"free/medkit_1.wav","free/medkit_2.wav","free/medkit_3.wav"})
nut.voice.register("combine", "спасибо_свобода", "", {"free/thanx_1.wav","free/thanx_2.wav","free/thanx_3.wav","free/thanx_4.wav","free/thanx_5.wav"})
nut.voice.register("combine", "к_лидеру_свобода", "", {"free/meet_use_no_talk_leader_1.wav","free/meet_use_no_talk_leader_2.wav","free/meet_use_no_talk_leader_3.wav"})
nut.voice.register("combine", "привет_свобода", "", {"free/meet_hello_1.wav","free/meet_hello_2.wav","free/meet_hello_3.wav"})
nut.voice.register("combine", "отвали_свобода", "", {"free/meet_use_no_default_1.wav","free/meet_use_no_default_2.wav","free/meet_use_no_default_3.wav"})
nut.voice.register("combine", "враг_убить_свобода", "", {"free/enemy_1.wav","free/enemy_2.wav","free/enemy_3.wav","free/enemy_4.wav","free/enemy_5.wav"})
nut.voice.register("combine", "враг_ранен_свобода", "", {"free/enemy_hit_1.wav","free/enemy_hit_2.wav","free/enemy_hit_3.wav","free/enemy_hit_4.wav","free/enemy_hit_5.wav","free/enemy_hit_6.wav"})
nut.voice.register("combine", "враг_потерян_свобода", "", {"free/enemy_lost_1.wav","free/enemy_lost_2.wav","free/enemy_lost_3.wav","free/enemy_lost_4.wav","free/enemy_lost_5.wav","free/enemy_lost_6.wav"})
nut.voice.register("combine", "бой_окончен_свобода", "", {"free/relax_1.wav","free/relax_2.wav","free/relax_3.wav"})
nut.voice.register("combine", "союзник_убит_свобода", "", {"free/tolls_1.wav","free/tolls_2.wav","free/tolls_3.wav","free/tolls_4.wav"})
nut.voice.register("combine", "осмотреться_свобода", "", {"free/wait_1.wav","free/wait_2.wav","free/wait_3.wav","free/wait_4.wav","free/wait_5.wav"})

nut.voice.register("combine", "атака_долг", "", {"dolg/attack_1.wav", "dolg/attack_2.wav", "dolg/attack_3.wav", "dolg/attack_4.wav", "dolg/attack_5.wav", "dolg/attack_6.wav"})
nut.voice.register("combine", "анекдоты_долг", "", {"dolg/joke_1.wav", "dolg/joke_2.wav", "dolg/joke_3.wav", "dolg/joke_4.wav", "dolg/joke_5.wav", "dolg/joke_6.wav", "dolg/joke_7.wav", "dolg/joke_8.wav", "dolg/joke_9.wav", "dolg/joke_10.wav"})
nut.voice.register("combine", "смех_долг", "", {"dolg/laughter_1.wav", "dolg/laughter_2.wav", "dolg/laughter_3.wav", "dolg/laughter_4.wav"})
nut.voice.register("combine", "плохой_хабар_долг", "", {"dolg/loot_bad_1.wav", "dolg/loot_bad_2.wav", "dolg/loot_bad_3.wav"})
nut.voice.register("combine", "плохая_шутка_долг", "", {"dolg/reaction_joke_1.wav", "dolg/reaction_joke_2.wav", "dolg/reaction_joke_3.wav", "dolg/reaction_joke_4.wav"})
nut.voice.register("combine", "поиск_хараба_долг", "", {"dolg/loot_begin_1.wav", "dolg/loot_begin_2.wav", "dolg/loot_begin_3.wav"})
nut.voice.register("combine", "хороший_хабар_долг", "", {"dolg/loot_good_1.wav", "dolg/loot_good_2.wav", "dolg/loot_good_3.wav"})
nut.voice.register("combine", "ожидание_долг", "", {"dolg/idle_1.wav", "dolg/idle_2.wav", "dolg/idle_3.wav", "dolg/idle_4.wav", "dolg/idle_5.wav", "dolg/idle_6.wav", "dolg/idle_7.wav", "dolg/idle_8.wav", "dolg/idle_9.wav", "dolg/idle_10.wav", "dolg/idle_11.wav", "dolg/idle_12.wav", "dolg/idle_13.wav", "dolg/idle_14.wav", "dolg/idle_15.wav", "dolg/idle_16.wav", "dolg/idle_17.wav", "dolg/idle_18.wav", "dolg/idle_19.wav", "dolg/idle_20.wav", "dolg/idle_21.wav", "dolg/idle_22.wav", "dolg/idle_23.wav", "dolg/idle_24.wav", "dolg/idle_25.wav", "dolg/idle_26.wav", "dolg/idle_27.wav", "dolg/idle_28.wav", "dolg/idle_29.wav", "dolg/idle_30.wav", "dolg/idle_31.wav", "dolg/idle_32.wav", "dolg/idle_33.wav", "dolg/idle_34.wav", "dolg/idle_35.wav", "dolg/idle_36.wav", "dolg/idle_37.wav", "dolg/idle_38.wav", "dolg/idle_39.wav", "dolg/idle_40.wav", "dolg/idle_42.wav", "dolg/idle_41.wav", "dolg/idle_43.wav", "dolg/idle_44.wav", "dolg/idle_45.wav", "dolg/idle_46.wav", "dolg/idle_47.wav", "dolg/idle_48.wav", "dolg/idle_49.wav", "dolg/idle_50.wav", "dolg/idle_51.wav", "dolg/idle_52.wav", "dolg/idle_53.wav"})
nut.voice.register("combine", "добавиние_долг", "", {"dolg/kill_wounded_1.wav", "dolg/kill_wounded_2.wav", "dolg/kill_wounded_3.wav", "dolg/kill_wounded_4.wav", "dolg/kill_wounded_5.wav"})
nut.voice.register("combine", "помогите_долг", "", {"dolg/help_1.wav", "dolg/help_2.wav", "dolg/help_3.wav", "dolg/help_4.wav", "dolg/help_5.wav", "dolg/help_6.wav", "dolg/help_7.wav", "dolg/help_8.wav"})
nut.voice.register("combine", "оружие_убрал_долг", "", {"dolg/dropweapon_1.wav", "dolg/dropweapon_2.wav", "dolg/dropweapon_3.wav", "dolg/dropweapon_4.wav", "dolg/dropweapon_5.wav", "dolg/dropweapon_6.wav", "dolg/dropweapon_7.wav"})
nut.voice.register("combine", "обходи_долг", "", {"dolg/detour_1.wav","dolg/detour_2.wav","dolg/detour_3.wav","dolg/detour_4.wav","dolg/detour_5.wav"})
nut.voice.register("combine", "поиск_противника_долг", "", {"dolg/search_1.wav","dolg/search_2.wav","dolg/search_3.wav","dolg/search_4.wav","dolg/search_5.wav","dolg/search_6.wav","dolg/search_7.wav","dolg/search_8.wav"})
nut.voice.register("combine", "лечить_долг", "", {"dolg/medkit_1.wav","dolg/medkit_2.wav","dolg/medkit_3.wav"})
nut.voice.register("combine", "спасибо_долг", "", {"dolg/thanx_1.wav","dolg/thanx_2.wav","dolg/thanx_3.wav","dolg/thanx_4.wav","dolg/thanx_5.wav","dolg/thanx_6.wav"})
nut.voice.register("combine", "к_лидеру_долг", "", {"dolg/meet_use_no_talk_leader_1.wav","dolg/meet_use_no_talk_leader_2.wav","dolg/meet_use_no_talk_leader_3.wav"})
nut.voice.register("combine", "привет_долг", "", {"dolg/meet_hello_1.wav","dolg/meet_hello_2.wav","dolg/meet_hello_3.wav"})
nut.voice.register("combine", "отвали_долг", "", {"dolg/meet_use_no_default_1.wav","dolg/meet_use_no_default_2.wav","dolg/meet_use_no_default_3.wav"})
nut.voice.register("combine", "враг_долг", "", {"dolg/enemy_1.wav","dolg/enemy_2.wav","dolg/enemy_3.wav","dolg/enemy_4.wav","dolg/enemy_5.wav"})
nut.voice.register("combine", "враг_убит_долг", "", {"dolg/enemy_down_1.wav","dolg/enemy_down_2.wav","dolg/enemy_down_3.wav","dolg/enemy_down_4.wav","dolg/enemy_down_5.wav"})
nut.voice.register("combine", "враг_ранен_долг", "", {"dolg/enemy_hit_1.wav","dolg/enemy_hit_2.wav","dolg/enemy_hit_3.wav","dolg/enemy_hit_4.wav","dolg/enemy_hit_5.wav","dolg/enemy_hit_6.wav","dolg/enemy_hit_7.wav"})
nut.voice.register("combine", "враг_потерян_долг", "", {"dolg/enemy_lost_1.wav","dolg/enemy_lost_2.wav","dolg/enemy_lost_3.wav","dolg/enemy_lost_4.wav","dolg/enemy_lost_5.wav"})
nut.voice.register("combine", "союзник_ранег_долг", "", {"dolg/hit_friend_1.wav","dolg/hit_friend_2.wav","dolg/hit_friend_3.wav","dolg/hit_friend_4.wav"})
nut.voice.register("combine", "окончание_боя_долг", "", {"dolg/relax_1.wav","dolg/relax_2.wav","dolg/relax_3.wav"})
nut.voice.register("combine", "союзник_убит_долг", "", {"dolg/tolls_1.wav","dolg/tolls_2.wav","dolg/tolls_3.wav","dolg/tolls_4.wav","dolg/tolls_5.wav"})
nut.voice.register("combine", "осмотреться_долг", "", {"dolg/wait_1.wav","dolg/wait_2.wav","dolg/wait_3.wav","dolg/wait_4.wav","dolg/wait_5.wav"})

nut.voice.register("combine", "атака_наемники", "", {"kill/attack_1.wav", "kill/attack_2.wav", "kill/attack_3.wav", "kill/attack_4.wav", "kill/attack_5.wav", "kill/attack_6.wav", "kill/attack_7.wav", "kill/attack_8.wav"})
nut.voice.register("combine", "плохой_хабар_наемники", "", {"kill/loot_bad_1.wav", "kill/loot_bad_2.wav", "kill/loot_bad_3.wav"})
nut.voice.register("combine", "поиск_хабара_наемники", "", {"kill/loot_begin_1.wav", "kill/loot_begin_2.wav", "kill/loot_begin_3.wav"})
nut.voice.register("combine", "хороший_хабар_наемники", "", {"kill/loot_good_1.wav", "kill/loot_good_2.wav", "kill/loot_good_3.wav"})
nut.voice.register("combine", "ожидание_наемники", "", {"kill/idle_1.wav", "kill/idle_2.wav", "kill/idle_3.wav", "kill/idle_4.wav", "kill/idle_5.wav", "kill/idle_6.wav", "kill/idle_7.wav", "kill/idle_8.wav", "kill/idle_9.wav", "kill/idle_10.wav", "kill/idle_11.wav", "kill/idle_12.wav", "kill/idle_13.wav", "kill/idle_14.wav", "kill/idle_15.wav", "kill/idle_16.wav", "kill/idle_17.wav", "kill/idle_18.wav", "kill/idle_19.wav", "kill/idle_20.wav", "kill/idle_21.wav", "kill/idle_22.wav", "kill/idle_23.wav", "kill/idle_24.wav", "kill/idle_25.wav", "kill/idle_26.wav", "kill/idle_27.wav", "kill/idle_28.wav", "kill/idle_29.wav", "kill/idle_30.wav"})
nut.voice.register("combine", "добавиние_наемники", "", {"kill/kill_wounded_1.wav", "kill/kill_wounded_2.wav", "kill/kill_wounded_3.wav", "kill/kill_wounded_4.wav", "kill/kill_wounded_5.wav"})
nut.voice.register("combine", "помогите_наемники", "", {"kill/help_1.wav", "kill/help_2.wav", "kill/help_3.wav", "kill/help_4.wav", "kill/help_5.wav", "kill/help_6.wav", "kill/help_7.wav"})
nut.voice.register("combine", "обходи_наемники", "", {"kill/detour_1.wav","kill/detour_2.wav","kill/detour_3.wav","kill/detour_4.wav","kill/detour_5.wav","kill/detour_6.wav","kill/detour_7.wav","kill/detour_8.wav","kill/detour_9.wav","kill/detour_10.wav"})
nut.voice.register("combine", "искать_наемники", "", {"kill/search_1.wav","kill/search_2.wav","kill/search_3.wav","kill/search_4.wav","kill/search_5.wav","kill/search_6.wav","kill/search_7.wav","kill/search_8.wav","kill/search_9.wav","kill/search_10.wav"})
nut.voice.register("combine", "лечить_наемники", "", {"kill/medkit_1.wav","kill/medkit_2.wav","kill/medkit_3.wav"})
nut.voice.register("combine", "спасибо_наемники", "", {"kill/thanx_1.wav","kill/thanx_2.wav","kill/thanx_3.wav"})
nut.voice.register("combine", "враг_наемники", "", {"kill/enemy_1.wav","kill/enemy_2.wav","kill/enemy_3.wav","kill/enemy_4.wav","kill/enemy_5.wav","kill/enemy_6.wav","kill/enemy_7.wav","kill/enemy_8.wav","kill/enemy_9.wav","kill/enemy_10.wav"})
nut.voice.register("combine", "союзника_убили_наемники", "", {"kill/tolls_1.wav","kill/tolls_2.wav","kill/tolls_3.wav","kill/tolls_4.wav","kill/tolls_5.wav"})

nut.voice.register("combine", "атака_военные", "", {"voen/attack_1.wav", "voen/attack_2.wav", "voen/attack_3.wav"})
nut.voice.register("combine", "помогите_военные", "", {"voen/help_1.wav", "voen/help_2.wav", "voen/help_3.wav", "voen/help_4.wav", "voen/help_5.wav", "voen/help_6.wav"})
nut.voice.register("combine", "ожидание_военные", "", {"voen/idle_1.wav", "voen/idle_2.wav", "voen/idle_3.wav", "voen/idle_4.wav", "voen/idle_5.wav", "voen/idle_6.wav", "voen/idle_7.wav", "voen/idle_8.wav", "voen/idle_9.wav", "voen/idle_10.wav", "voen/idle_11.wav", "voen/idle_12.wav", "voen/idle_13.wav", "voen/idle_14.wav", "voen/idle_15.wav", "voen/idle_16.wav", "voen/idle_17.wav", "voen/idle_18.wav", "voen/idle_19.wav", "voen/idle_20.wav", "voen/idle_21.wav", "voen/idle_22.wav", "voen/idle_23.wav", "voen/idle_24.wav", "voen/idle_25.wav", "voen/idle_26.wav", "voen/idle_27.wav", "voen/idle_28.wav"})
nut.voice.register("combine", "анекдоры_военные", "", {"voen/joke_1.wav", "voen/joke_2.wav", "voen/joke_3.wav", "voen/joke_4.wav", "voen/joke_5.wav", "voen/joke_6.wav", "voen/joke_7.wav", "voen/joke_8.wav", "voen/joke_9.wav", "voen/joke_10.wav", "voen/joke_11.wav"})
nut.voice.register("combine", "добивание_военные", "", {"voen/kill_wounded_1.wav", "voen/kill_wounded_2.wav", "voen/kill_wounded_3.wav", "voen/kill_wounded_4.wav", "voen/kill_wounded_5.wav"})
nut.voice.register("combine", "смех_военные", "", {"voen/laughter_1.wav", "voen/laughter_2.wav", "voen/laughter_3.wav", "voen/laughter_4.wav", "voen/laughter_5.wav", "voen/laughter_6.wav", "voen/laughter_7.wav"})
nut.voice.register("combine", "плохой_хабар_военные", "", {"voen/loot_bad_1.wav", "voen/loot_bad_2.wav", "voen/loot_bad_3.wav"})
nut.voice.register("combine", "поиск_хабара_военные", "", {"voen/loot_begin_1.wav", "voen/loot_begin_2.wav", "voen/loot_begin_3.wav"})
nut.voice.register("combine", "хороший_хабар_вогенные", "", {"voen/loot_good_1.wav", "voen/loot_good_2.wav", "voen/loot_good_3.wav"})
nut.voice.register("combine", "лечить_военные", "", {"voen/medkit_1.wav","voen/medkit_2.wav","voen/medkit_3.wav"})
nut.voice.register("combine", "обходи_военные", "", {"voen/detour_1.wav","voen/detour_2.wav","voen/detour_3.wav","voen/detour_4.wav","voen/detour_5.wav","voen/detour_6.wav"})
nut.voice.register("combine", "спасибо_военные", "", {"voen/thanx_1.wav","voen/thanx_2.wav","voen/thanx_3.wav"})
nut.voice.register("combine", "к_лидеру_военные", "", {"voen/meet_use_no_talk_leader_1.wav","voen/meet_use_no_talk_leader_2.wav","voen/meet_use_no_talk_leader_3.wav"})
nut.voice.register("combine", "поиск_противника_военные", "", {"voen/search_1.wav","voen/search_2.wav","voen/search_3.wav","voen/search_4.wav","voen/search_5.wav"})
nut.voice.register("combine", "отвали_военные", "", {"voen/meet_use_no_default_1.wav","voen/meet_use_no_default_2.wav","voen/meet_use_no_default_3.wav"})
nut.voice.register("combine", "враг_военные", "", {"voen/enemy_1.wav","voen/enemy_2.wav","voen/enemy_3.wav","voen/enemy_4.wav","voen/enemy_5.wav"})
nut.voice.register("combine", "враг_убит_военные", "", {"voen/enemy_down_1.wav","voen/enemy_down_2.wav","voen/enemy_down_3.wav","voen/enemy_down_4.wav"})
nut.voice.register("combine", "враг_ранен_военные", "", {"voen/enemy_hit_1.wav","voen/enemy_hit_2.wav","voen/enemy_hit_3.wav","voen/enemy_hit_4.wav","voen/enemy_hit_5.wav"})
nut.voice.register("combine", "враг_потерян_военные", "", {"voen/enemy_lost_1.wav","voen/enemy_lost_2.wav","voen/enemy_lost_3.wav","voen/enemy_lost_4.wav","voen/enemy_lost_5.wav","voen/enemy_lost_6.wav"})
nut.voice.register("combine", "союзник_ранен_военные", "", {"voen/hit_friend_1.wav","voen/hit_friend_2.wav","voen/hit_friend_3.wav","voen/hit_friend_4.wav"})
nut.voice.register("combine", "окончание_боя_военные", "", {"voen/relax_1.wav","voen/relax_2.wav","voen/relax_3.wav"})
nut.voice.register("combine", "союзник_убит_военные", {"voen/tolls_1.wav","voen/tolls_2.wav","voen/tolls_3.wav","voen/tolls_4.wav"})
nut.voice.register("combine", "осмотретьс_военные", "", {"voen/wait_1.wav","voen/wait_2.wav","voen/wait_3.wav","voen/wait_4.wav","voen/wait_5.wav"})
