local PANEL = {}

function PANEL:Init()
	self:SetSize(200, 340)
	self:Center()
	self:SetTitle("")
	self:MakePopup()
	function self:Paint( w, h )
		local material = Material("ui/ui_loot_interface.png") 
		surface.SetDrawColor(color_white) 
		surface.SetMaterial(material) 
		surface.DrawTexturedRect(0, 0, w, h) 
	end
	self:ShowCloseButton( false )
	self.list = self:Add("PanelList")
	self.list:Dock(FILL)
	self.list:DockMargin(0, 5, 0, 0)
	self.list:SetSpacing(5)
	function self.list:Paint( w, h )
		local material = Material("ui/ui_noimage.png") 
		surface.SetDrawColor(color_white) 
		surface.SetMaterial(material) 
		surface.DrawTexturedRect(0, 0, w, h) 
	end
	self.list:SetPadding(5)
	self.list:EnableVerticalScrollbar()
	
	self:loadActs()
end

function PANEL:loadActs()
	local actsit = self.list:Add("DButton")
	actsit:SetFont("Default")
	--actsit:Dock(LEFT)
	function actsit:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actsit:SetSize(120, 17)
	actsit:SetPos(35, 0)	
	actsit:SetFont("ChatFontMisery1")
	actsit:SetTextColor(Color(210, 180, 140))
	--actsit:SetTall(20)
	actsit:DockMargin(0, 5, 0, 0)
	actsit:SetText("Сесть")
	function actsit:DoClick()
		nut.command.send("actsit")
		nutActsMenu:Close()
	end
	
	local actinjured = self.list:Add("DButton")
	actinjured:SetFont("Default")
	--actinjured:Dock(TOP)
	function actinjured:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actinjured:SetSize(120, 17)
	actinjured:SetPos(35, 20)
	actinjured:SetFont("ChatFontMisery1")
	actinjured:SetTextColor(Color(210, 180, 140))
	actinjured:DockMargin(0, 5, 0, 0)
	actinjured:SetText("Лечь на бок")
	function actinjured:DoClick()
		nut.command.send("actinjured", 1)
		nutActsMenu:Close()
	end
	
	local actinjured1 = self.list:Add("DButton")
	actinjured1:SetFont("Default")
	--actinjured1:Dock(TOP)
	function actinjured1:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actinjured1:SetSize(120, 17)
	actinjured1:SetPos(35, 40)
	actinjured1:SetFont("ChatFontMisery1")
	actinjured1:SetTextColor(Color(210, 180, 140))
	actinjured1:DockMargin(0, 5, 0, 0)
	actinjured1:SetText("Лечь на спину")
	function actinjured1:DoClick()
		nut.command.send("actrest")
		nutActsMenu:Close()
	end
	
	local actarrest = self.list:Add("DButton")
	actarrest:SetFont("Default")
	--actarrest:Dock(TOP)
	function actarrest:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actarrest:SetSize(120, 17)
	actarrest:SetPos(35, 60)
	actarrest:SetFont("ChatFontMisery1")
	actarrest:SetTextColor(Color(210, 180, 140))
	actarrest:DockMargin(0, 5, 0, 0)
	actarrest:SetText("Руки вверх")
	function actarrest:DoClick()
		nut.command.send("acthandup")
		nutActsMenu:Close()
	end
	
	local actcheer = self.list:Add("DButton")
	actcheer:SetFont("Default")
	--actcheer:Dock(TOP)
	function actcheer:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actcheer:SetSize(120, 17)
	actcheer:SetPos(35, 80)
	actcheer:SetFont("ChatFontMisery1")
	actcheer:SetTextColor(Color(210, 180, 140))
	actcheer:DockMargin(0, 5, 0, 0)
	actcheer:SetText("Руки в карманы")
	function actcheer:DoClick()
		nut.command.send("actband1")
		nutActsMenu:Close()
	end
	
	local actcheer1 = self.list:Add("DButton")
	actcheer1:SetFont("Default")
	--actcheer1:Dock(TOP)
	function actcheer1:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actcheer1:SetSize(120, 17)
	actcheer1:SetPos(35, 100)
	actcheer1:SetFont("ChatFontMisery1")
	actcheer1:SetTextColor(Color(210, 180, 140))
	actcheer1:DockMargin(0, 5, 0, 0)
	actcheer1:SetText("Руки накрест")
	function actcheer1:DoClick()
		nut.command.send("actstoit")
		nutActsMenu:Close()
	end
	
	local actcheer2 = self.list:Add("DButton")
	actcheer2:SetFont("Default")
	--actcheer2:Dock(TOP)
	function actcheer2:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actcheer2:SetSize(120, 17)
	actcheer2:SetPos(35, 120)
	actcheer2:SetFont("ChatFontMisery1")
	actcheer2:SetTextColor(Color(210, 180, 140))
	actcheer2:DockMargin(0, 5, 0, 0)
	actcheer2:SetText("Встать на колени")
	function actcheer2:DoClick()
		nut.command.send("actkoleni")
		nutActsMenu:Close()
	end
	
	local acthere = self.list:Add("DButton")
	acthere:SetFont("Default")
	--acthere:Dock(TOP)
	function acthere:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	acthere:SetSize(120, 17)
	acthere:SetPos(35, 140)
	acthere:SetFont("ChatFontMisery1")
	acthere:SetTextColor(Color(210, 180, 140))
	acthere:DockMargin(0, 5, 0, 0)
	acthere:SetText("Руки за спиной")
	function acthere:DoClick()
		nut.command.send("actbackhands")
		nutActsMenu:Close()
	end
	
	local acthere2 = self.list:Add("DButton")
	acthere2:SetFont("Default")
	--acthere2:Dock(TOP)
	function acthere2:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	acthere2:SetSize(120, 17)
	acthere2:SetPos(35, 160)
	acthere2:SetFont("ChatFontMisery1")
	acthere2:SetTextColor(Color(210, 180, 140))
	acthere2:DockMargin(169, 169, 169, 0)
	acthere2:SetText("Поднять оружие")
	function acthere2:DoClick()
		nut.command.send("actbackweaponup")
		nutActsMenu:Close()
	end
	
	local actsitwall = self.list:Add("DButton")
	actsitwall:SetFont("Default")
	--actsitwall:Dock(TOP)
	function actsitwall:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actsitwall:SetSize(120, 17)
	actsitwall:SetPos(35, 180)
	actsitwall:SetFont("ChatFontMisery1")
	actsitwall:SetTextColor(Color(210, 180, 140))
	actsitwall:DockMargin(0, 5, 0, 0)
	actsitwall:SetText("Присесть")
	function actsitwall:DoClick()
		nut.command.send("actjustsit")
		nutActsMenu:Close()
	end
	
	local actsitwall1 = self.list:Add("DButton")
	actsitwall1:SetFont("Default")
	--actsitwall1:Dock(TOP)
	function actsitwall1:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actsitwall1:SetSize(120, 17)
	actsitwall1:SetPos(35, 200)
	actsitwall1:SetFont("ChatFontMisery1")
	actsitwall1:SetTextColor(Color(210, 180, 140))
	actsitwall1:DockMargin(0, 5, 0, 0)
	actsitwall1:SetText("Отдать честь")
	function actsitwall1:DoClick()
		nut.command.send("actchest")
		nutActsMenu:Close()
	end
	
	local actstand = self.list:Add("DButton")
	actstand:SetFont("Default")
	--actstand:Dock(TOP)
	function actstand:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actstand:SetSize(120, 17)
	actstand:SetPos(35, 220)
	actstand:SetFont("ChatFontMisery1")
	actstand:SetTextColor(Color(210, 180, 140))
	actstand:DockMargin(0, 5, 0, 0)
	actstand:SetText("Приседать")
	function actstand:DoClick()
		nut.command.send("actprisid")
		nutActsMenu:Close()
	end
	
	local actstand1 = self.list:Add("DButton")
	actstand1:SetFont("Default")
	--actstand1:Dock(TOP)
	function actstand1:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actstand1:SetSize(120, 17)
	actstand1:SetPos(35, 240)
	actstand1:SetFont("ChatFontMisery1")
	actstand1:SetTextColor(Color(210, 180, 140))
	actstand1:DockMargin(0, 5, 0, 0)
	actstand1:SetText("Убрать оружие!")
	function actstand1:DoClick()
		nut.command.send("acthidegun")
		nutActsMenu:Close()
	end
	
	local actstand2 = self.list:Add("DButton")
	actstand2:SetFont("Default")
	--actstand2:Dock(TOP)
	function actstand2:Paint( w, h )
			local material = Material("ui/trade_but.png") 
			surface.SetDrawColor(color_white) 
			surface.SetMaterial(material) 
			surface.DrawTexturedRect(0, 0, w, h) 
	end
	actstand2:SetSize(120, 17)
	actstand2:SetPos(35, 260)
	actstand2:SetFont("ChatFontMisery1")
	actstand2:SetTextColor(Color(210, 180, 140))
	actstand2:DockMargin(0, 5, 0, 0)
	actstand2:SetText("Облокотиться")
	function actstand2:DoClick()
		nut.command.send("actstol")
		nutActsMenu:Close()
	end
end

vgui.Register("nutActsMenu", PANEL, "DFrame")
netstream.Hook("nutActsMenu", function()
	nutActsMenu = vgui.Create("nutActsMenu")
end)